services:
  moni:                                                 # Moni Bot and Watchdog
    image: podkosa/moni
    restart: always
    ports: 
      - "6767:6767"
    volumes:
    - './settings.yml:/moni/settings.yml'
    - '~/.ssh/:/root/.ssh:ro'                           # For SSH dependent Checkers (e.g. DockerChecker). Make sure to grant Unix ownership/permissions.
    # - './logs/:/moni/logs'                            # For logging to file (LoggerHandler)

  # moni_watchdog:                                      # Run Watchdog separately
  #   image: podkosa/moni
  #   restart: always
  #   command: ./watchdog.py
  #   volumes:
  #   - './settings.yml:/moni/settings.yml'
  #  # - './logs/:/moni/logs'
