on:
  push:
    branches:
    - main
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Dockerhub Readme
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_KEY }}
        repository: podkosa/moni
        readme: "./README.md"
